name: qdrant_final_project

services:
  qdrant:
    container_name: qdrant
    hostname: qdrant
    build:
      context: .
      dockerfile: ./Dockerfile.qdrant
    networks:
      - qdrant_network
    ports:
      - "6333:6333"
      - "6334:6334"
      - "6335:6335"
    volumes:
      - qdrant_storage:/qdrant/storage
    deploy:
      resources:
        reservations:
          cpus: '2.0'
          memory: 2G
        limits:
          cpus: '4.0'
          memory: 4G
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  dev_host:
    container_name: dev_host
    hostname: dev_host
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev_host
    env_file:
      - .env.dev_host
    networks:
      - qdrant_network
    ports:
      - "8000:8000"
    volumes:
      - ../:/workspace
    command: sleep infinity
    deploy:             
      resources:
        reservations:
            cpus: '4.0'
            memory: 8G 
        limits:
          cpus: '8.0'
          memory: 16G
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped

  vllm-gemma4-12b:
    container_name: vllm-gemma4-12b
    hostname: vllm-gemma4-12b
    image: vllm/vllm-openai:v0.29.0-cu129
    env_file:
      - .env.vllm
    volumes:
      - ./volumes/vllm/huggingface:/root/.cache/huggingface
    shm_size: "8gb"
    networks:
      - qdrant_network
    ports:
      - "127.0.0.1:8001:8000"
    healthcheck:
        test:
          [
            "CMD-SHELL",
            "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)\""
          ]
    command: >
      google/gemma-4-12B-it-qat-w4a16-ct
      --served-model-name gemma-4-12b-it
      --tensor-parallel-size 1
      --enable-auto-tool-choice
      --tool-call-parser gemma4
      --chat-template examples/tool_chat_template_gemma4.jinja
      --reasoning-parser gemma4
      --max-model-len 16384
      --gpu-memory-utilization 0.85
      --language-model-only
      --host 0.0.0.0
      --port 8000
    deploy:
      resources:
        reservations:
          cpus: "2.0"
          memory: 8G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          cpus: "4.0"
          memory: 14G
    restart: unless-stopped


networks:
  qdrant_network:
    driver: bridge

volumes:
  qdrant_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/qdrant

configs:
  qdrant_config:
    file: ./production.yaml